# credofaster_partner_api
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module CredofasterPartnerApi
  # Payload the Partner receives on for each Event
  class EventCallbackPayload < BaseModel
    # This is shared by the system and should be referred when doing any
    # debugging
    # @return [String]
    attr_accessor :event_id

    # Contains the EVENT type.  detailed list of this can be shared on Request
    # to the admin
    # @return [String]
    attr_accessor :event_type

    # For Events that are related with the Clients Request, you will get a
    # Request ID that was generate by the system when you made a  service call
    # @return [String]
    attr_accessor :request_id

    # Contains any addition fields,(CAN BE NESTED). See the PDF for more details
    # @return [Object]
    attr_accessor :event_data

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['event_id'] = 'EventId'
      @_hash['event_type'] = 'EventType'
      @_hash['request_id'] = 'RequestId'
      @_hash['event_data'] = 'EventData'
      @_hash
    end

    def initialize(event_id = '123456789',
                   event_type = 'QUEUED',
                   event_data = nil,
                   request_id = nil)
      @event_id = event_id
      @event_type = event_type
      @request_id = request_id
      @event_data = event_data
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      event_id = hash['EventId'] ||= '123456789'
      event_type = hash['EventType'] ||= 'QUEUED'
      event_data = hash['EventData']
      request_id = hash['RequestId']

      # Create object from extracted values.
      EventCallbackPayload.new(event_id,
                               event_type,
                               event_data,
                               request_id)
    end
  end
end
