# credofaster_partner_api
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module CredofasterPartnerApi
  # EventCallbackFeedback Model.
  class EventCallbackFeedback < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :error_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :error_description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['error_code'] = 'ErrorCode'
      @_hash['error_description'] = 'ErrorDescription'
      @_hash
    end

    def initialize(error_code = nil,
                   error_description = nil)
      @error_code = error_code
      @error_description = error_description
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      error_code = hash['ErrorCode']
      error_description = hash['ErrorDescription']

      # Create object from extracted values.
      EventCallbackFeedback.new(error_code,
                                error_description)
    end
  end
end
