# credofaster_partner_api
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module CredofasterPartnerApi
  # Initiator Model.
  class Initiator < BaseModel
    # Client Type Initiating the Request
    # @return [String]
    attr_accessor :type

    # Client ID Initiating the Request
    # @return [String]
    attr_accessor :id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['id'] = 'id'
      @_hash
    end

    def initialize(type = 'PARTNER',
                   id = '10001')
      @type = type
      @id = id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash['type'] ||= 'PARTNER'
      id = hash['id'] ||= '10001'

      # Create object from extracted values.
      Initiator.new(type,
                    id)
    end
  end
end
