# credofaster_partner_api
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module CredofasterPartnerApi
  # Response you get for A Request
  class PartnerAirtimeResponse < BaseModel
    # Code for the Request API Generated. 0: Success, Any other Error Code,
    # refer to ErrorCodes Page
    # @return [Integer]
    attr_accessor :error_code

    # Text Description
    # @return [String]
    attr_accessor :error_description

    # a UUID Returned for the Transaction
    # @return [UUID | String]
    attr_accessor :reference_id

    # Return of the Clients Request ID
    # @return [UUID | String]
    attr_accessor :request_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['error_code'] = 'ErrorCode'
      @_hash['error_description'] = 'ErrorDescription'
      @_hash['reference_id'] = 'ReferenceId'
      @_hash['request_id'] = 'RequestId'
      @_hash
    end

    def initialize(error_code = 0,
                   error_description = nil,
                   reference_id = nil,
                   request_id = nil)
      @error_code = error_code
      @error_description = error_description
      @reference_id = reference_id
      @request_id = request_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      error_code = hash['ErrorCode'] ||= 0
      error_description = hash['ErrorDescription']
      reference_id = hash['ReferenceId']
      request_id = hash['RequestId']

      # Create object from extracted values.
      PartnerAirtimeResponse.new(error_code,
                                 error_description,
                                 reference_id,
                                 request_id)
    end
  end
end
