# credofaster_partner_api
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module CredofasterPartnerApi
  # Balance Response
  class PartnerAirtimeBalanceResponse < BaseModel
    # Code for the Request API Generated. 0: Success, Any other Error Code,
    # refer to ErrorCodes Page
    # @return [Integer]
    attr_accessor :error_code

    # Text Description
    # @return [String]
    attr_accessor :error_description

    # Remaining Tentative Balance
    # @return [Long]
    attr_accessor :unit_balance

    # Limit of Units to Use.
    # @return [Long]
    attr_accessor :limit

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['error_code'] = 'ErrorCode'
      @_hash['error_description'] = 'ErrorDescription'
      @_hash['unit_balance'] = 'UnitBalance'
      @_hash['limit'] = 'Limit'
      @_hash
    end

    def initialize(error_code = 0,
                   error_description = 'Success.',
                   unit_balance = 0,
                   limit = 0)
      @error_code = error_code
      @error_description = error_description
      @unit_balance = unit_balance
      @limit = limit
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      error_code = hash['ErrorCode'] ||= 0
      error_description = hash['ErrorDescription'] ||= 'Success.'
      unit_balance = hash['UnitBalance'] ||= 0
      limit = hash['Limit'] ||= 0

      # Create object from extracted values.
      PartnerAirtimeBalanceResponse.new(error_code,
                                        error_description,
                                        unit_balance,
                                        limit)
    end
  end
end
