# credofaster_partner_api
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module CredofasterPartnerApi
  # RegisterCallbackRequest Model.
  class RegisterCallbackRequest < BaseModel
    # Define a reachable URL that accepts a JSON Payload as described below
    # @return [String]
    attr_accessor :url

    # Define the transactions per second we should use when pushing callbacks to
    # your side
    # @return [String]
    attr_accessor :tps

    # A comma separated value, containing the number of seconds to wait for any
    # retries and the max number of retries to do, when the clients endpoint
    # responds with an Error
    # @return [String]
    attr_accessor :retries

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['url'] = 'url'
      @_hash['tps'] = 'tps'
      @_hash['retries'] = 'retries'
      @_hash
    end

    def initialize(url = 'https://posthere.io/partner_test',
                   tps = '10',
                   retries = '1,5')
      @url = url
      @tps = tps
      @retries = retries
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      url = hash['url'] ||= 'https://posthere.io/partner_test'
      tps = hash['tps'] ||= '10'
      retries = hash['retries'] ||= '1,5'

      # Create object from extracted values.
      RegisterCallbackRequest.new(url,
                                  tps,
                                  retries)
    end
  end
end
