# credofaster_partner_api
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module CredofasterPartnerApi
  # RegisterCallbackResponse Model.
  class RegisterCallbackResponse < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :error_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :error_description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :registered_callback_url

    # Tracking RequestId
    # @return [UUID | String]
    attr_accessor :request_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['error_code'] = 'ErrorCode'
      @_hash['error_description'] = 'ErrorDescription'
      @_hash['registered_callback_url'] = 'RegisteredCallbackUrl'
      @_hash['request_id'] = 'RequestId'
      @_hash
    end

    def initialize(error_code = nil,
                   error_description = nil,
                   registered_callback_url = nil,
                   request_id = nil)
      @error_code = error_code
      @error_description = error_description
      @registered_callback_url = registered_callback_url
      @request_id = request_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      error_code = hash['ErrorCode']
      error_description = hash['ErrorDescription']
      registered_callback_url = hash['RegisteredCallbackUrl']
      request_id = hash['RequestId']

      # Create object from extracted values.
      RegisterCallbackResponse.new(error_code,
                                   error_description,
                                   registered_callback_url,
                                   request_id)
    end
  end
end
