# credofaster_partner_api
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

# CohesityManagementSdk
module CredofasterPartnerApi
  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration
    # Set the array parameter serialization method.
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    @array_serialization = 'indexed'

    # An enum for SDK environments.
    class Environment
      #PRODUCTION: Live Environment
      #SANDBOX: For Test Purpose
      #DEVELOPMENT: Development
      ENVIRONMENT = [PRODUCTION = 0, SANDBOX = 1, DEVELOPMENT = 2].freeze
    end

    # An enum for API servers.
    class Server
      SERVER = [DEFAULT = 0, MY_CALLBACK_ENDPOINT = 1].freeze
    end

    # The environment in which the SDK is running.
    @environment = Environment::SANDBOX

    # Assigned APIKey
    @api_key = 'XXXX-XXXX-XXXX-XXXX'

    # Assigned ClientId
    @client_id = 'ABCDEDFG1234'

    # All the environments the SDK can run in.
    @environments = {
      Environment::PRODUCTION => {
        Server::DEFAULT => 'https://api.partner.credofaster.co.ke',
        Server::MY_CALLBACK_ENDPOINT => 'https://posthere.io/dfd0-4d32-8ad9'
      },
      Environment::SANDBOX => {
        Server::DEFAULT => 'https://api-test.partner.credofaster.co.ke',
        Server::MY_CALLBACK_ENDPOINT => 'https://posthere.io/dfd0-4d32-8ad9'
      },
      Environment::DEVELOPMENT => {
        Server::DEFAULT => 'https://partner.credofaster.co.ke/crm_api/api/',
        Server::MY_CALLBACK_ENDPOINT => 'https://partner.credofaster.co.ke/crm_api/api/'
      }
    }

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] The server enum for which the base URI is
    # required.
    # @return [String] The base URI.
    def self.get_base_uri(server = Server::DEFAULT)
      environments[environment][server].clone
    end

    # The attribute accessors for public properties.
    class << self
      attr_accessor :array_serialization
      attr_accessor :environment
      attr_accessor :environments
      attr_accessor :api_key
      attr_accessor :client_id
    end
  end
end
