# credofaster_partner_api
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module CredofasterPartnerApi
  #  credofaster_partner_api client class.
  class CredofasterPartnerApiClient
    # Singleton access to main controller.
    # @return [MainController] Returns the controller instance.
    def main
      MainController.instance
    end

    # Singleton access to events controller.
    # @return [EventsController] Returns the controller instance.
    def events
      EventsController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end

    # Initializer with authentication and configuration parameters.
    def initialize(api_key: 'XXXX-XXXX-XXXX-XXXX', client_id: 'ABCDEDFG1234')
      Configuration.api_key = api_key if
        api_key
      Configuration.client_id = client_id if
        client_id
    end
  end
end
